#+TITLE: Introdução à Convenção de Viena sobre Venda Internacional de Mercadorias
#+AUTHOR: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: date:nil toc:nil num:nil
#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex


* 1. Contexto histórico
** A) Primeiros passos

Os primeiros esforços de unificação legislativa do Direito da venda internacional começaram nos anos 20 do século passado. Normalmente atribui-se a primeira sugestão de unificação da lei do contrato de venda internacional de mercadorias a Ernst Rabel.

Ernst Rabel foi diretor do Instituto, à data, Kaiser Wilhelm - hoje Max Planck -, para o Direito estrangeiro e Direito Internacional Privado, criado em 1926. Um dos estudos efetuados pelo Instituto foi um estudo comparativo sobre o Direito da venda internacional de mercadorias.

Também em 1926 a Liga das Nações fundou, em Roma, o /Institut international pour l’unification du droit privé/ (UNIDROIT). O UNIDROIT foi um passo importante para a unificação do Direito da venda internacional de mercadorias. O seu [[https://www.unidroit.org/english/presentation/statute.pdf][Estatuto]] estabelece, no artigo 1.º a missão de:

#+begin_quote
(...) examine  ways  of  harmonising  and  coordinating  the private law of States and of groups of States, and to prepare gradually for the adoption by the various States of uniform rules of private law.
#+end_quote

Em 1928, Ernst Rabel, membro da direção do UNIDROIT, sugeriu que o primeiro projeto de unificação fosse sobre o Direito material da venda internacional de mercadorias. Rabel apresentou, em 1929, dois relatórios: /(i)/ um relatório provisório relativo às possibilidades de unificação do Direito da venda de mercadorias[fn:1]; e /(ii)/ um relatório sobre o Direito comparado da venda internacional de mercadorias, que viria a ser conhecido por "Relatório Azul"[fn:2].

Em 1930, o UNIDROIT estabeleceu uma comissão com vista a trabalhar no projeto de lei uniforme de venda. A Comissão contava entre os seus membros, para além de Rabel, com representantes dos sistemas jurídicos do /Common Law/, do sistema francês, alemão e dos países Escandinavos.

O primeiro /draft/ foi apresentado em 1935. Este /draft/ era fortemente influenciado pelo estudo de Direito comparado da venda internacional de Rabel.

Quatro anos mais tarde, em 1939, foi apresentado um segundo /draft/. A Segunda Guerra Mundial suspendeu as negociações que só retomaram em 1950.

** B) As Convenções UNIDROIT de 1964
:PROPERTIES:
:ID:       bcab76a9-f161-4285-b7a5-3e8ca6f36a56
:END:

Em 1951, o UNIDROIT realizou uma conferência de 21 Estados na Haia. Foram enviados novos /drafts/ do projeto de lei uniforme da venda internacional de mercadorias em 1956 e 1963 e iniciaram-se trabalhos no projeto de lei uniforme sobre a formação de contratos de venda internacional de mercadorias.

Em 1964, realizou-se nova conferência diplomática na Haia, desta feita com a participação de 28 Estados, que culminou com a aprovação das duas convenções UNIDROIT de 1964:  uma contendo a [[https://www.unidroit.org/instruments/international-sales/ulis-1964/][Lei uniforme sobre venda internacional de mercadorias]] e outra a [[https://www.unidroit.org/instruments/international-sales/ulfc-1964/][Lei uniforme sobre a formação dos contratos de venda internacional de mercadorias]].

O objetivo destas Convenções era a unificação mundial do Direita da venda internacional de mercadorias. Apesar de terem entrado internacionalmente em vigor, estas Convenções não podem considerar um sucesso quando analisadas em função daquele objetivo: apenas nove Estados se vincularam a estas Convenções.

As razões avançadas para este reduzido número de Estados contratantes são variadas. As que me parecem mais relevantes são o elevado grau de abstração de vários conceitos fulcrais das leis uniformes e, sobretudo, a ideia de que as leis uniformes não tomaram em consideração os interesses dos Estados em vias de desenvolvimentos ou dos Estados de leste, que não participaram na elaboração e aprovação destas leis uniformes. Outra razão avançada é a não vinculação de alguns dos Estados mais importantes no comércio internacional, como os Estados Unidos da América e a França.

Ainda assim, estas duas leis uniformes foram relevantes. Elas tiveram uma relevante importância na prática jurisprudencial alemã, italiana, belga, luxemburguesa e holandesa. E marcaram também a elaboração da Convenção de Viena sobre Internacional de Mercadorias.

** C) A CNUDCI e a génese da CVIM

Em 1966 a Assembleia Geral das Nações Unidas estabeleceu a Comissão das Nações Unidas para o Direito Comercial Internacional (CNUDCI) como comissão permanente, com o mandato de promover a progressiva harmonização e unificação do Direito do comércio internacional.

A primeira questão com que se deparou, no que se referia à promoção da unificação do direito da venda internacional de mercadorias, era a de tentar promover uma adoção mais ampla das Convenções de 1964, como fez com a Convenção de Nova Iorque de 1958 sobre o Reconhecimento e Execução de Sentenças Arbitrais Estrangeiras /ou/ preparar uma nova Convenção.

Para responder a esta questão enviou o texto das Convenções de 1964, juntamente com o Relatório Explicativo elaborado pelo Professor André Tunc, a vários Governos, pedindo comentários e a posição sobre uma eventual vinculação às Convenções. A CNUDCI chegou à conclusão de que as Convenções não seriam um sucesso: muitos Estados estavam preocupados que as Convenções refletiam as tradições e realidades económicas dos países  europeus.

A CNUDCI decidiu assim avançar para a elaboração de uma nova Convenção, que viria a ser a Convenção de Viena sobre Venda Internacional de Mercadorias.

O processo de elaboração da Convenção pode dividir-se em três fases.

A primeira fase decorreu entre 1970 e 1977. Foi constituído um Grupo de Trabalho que preparou projetos para as reuniões plenárias da CNUDCI. Estes projetos partiram da análise, pelo Grupo de Trabalho, das duas leis uniformes. Em 1976, o Grupo de Trabalho concluiu e aprovou, por unanimidade, o projeto de Convenção sobre a Venda Internacional de Mercadorias, que estabelecia os direitos e obrigações de vendedores e compradores na venda internacional. Em 1977, o Grupo de Trabalho concluiu o projeto de Convenção sobre a Formação do Contrato de Venda Internacional de Mercadorias.

O início da segunda fase dá-se com a reunião da CNUDCI em Viena, de maio a junho de 1977. Nesta reunião a CNUDCI reviu, concluiu e aprovou o projeto de Convenção sobre a Venda Internacional. Um ano mais tarde, em maio e junho de 1978, o projeto de Convenção sobre a formação do contrato foi analisado e foi decidido juntar os dois projetos. O projeto de Convenção sobre Contratos de Venda Internacional de Mercadorias foi concluído em junho de 1978 e ficou conhecido como o /New York Draft/.

O /New York Draft/ foi enviado para os governos dos Membros das Nações Unidas. Ele e os comentários recebidos foram a base da Convenção de Viena sobre a Venda Internacional de Mercadorias.

A terceira e última fase inicia-se com a Conferência das Nações Unidas que teve lugar em Viena, de 10 de março a 11 de abril de 1980. Participaram nesta conferência 62 Estados e 8 organizações internacionais. Foram formados dois comitês: o primeiro trabalhou as normas substantivas (arts. 1 a 88 da CVIM); o segundo as disposições finais (arts. 89 a 101) e preparou um protocolo para a Convenção sobre prescição em matéria de venda internacional de mercadorias, de modo a adaptar esta convenção à futura Convenção sobre a Venda Internacional de Mercadorias. A Convenção foi aprovada em 11 de março de 1980 e entrou internacionalmente em vigor em 1 de janeiro de 1988, doze meses passados da data da 10.ª adesão. Hoje são 94 os Estados contratantes, entre os quais a China, Brasil e Portugal. Angola não se vinculou a esta Convenção.


** D) Razões do sucesso da CVIM

Pode perguntar-se porque teve a Convenção sobre a Venda Internacional de Mercadorias sucesso e as Convenções da Haia de 1964 não.

A verdade é que a Convenção corrigiu aquele que parece ter sido o maior "pecado" das Convenções. Participaram na elaboração das Convenções da Haia 28 Estados, dos quais 19 eram da Europa Ocidental, 3 da Europa de Leste (mas a ex-URSS não participou) e apenas 5 eram da África, Ásia e América do Sul. Este desequilíbrio fomentou a perceção - certa ou errada, isso é irrelevante - de que as Convenções da Haia não tomavam em consideração os interesses de Estados que não os da Europa Ocidental.

A CNUDCI estabeleceu uma distribuição regional específica para os seus membros, de modo a garantir a representação das várias regiões geográficas e dos principais sistemas jurídicos e económicos mundiais. Assim, 9 membros eram da África, 7 membros da Ásia, 5 da Europa de leste, 6 da América do Sul e 9 dos Estados ocidentais.

Consequentemente, e em contraste com as Convenções da Haia de 1964, a Convenção sobre a Venda Internacional de Mercadorias procura conciliar diferentes tradições jurídicas e utiliza mais conceitos indeterminados de modo a facilitar a vinculação internacional de mais Estados. Nesse mesmo sentido, também parece ser de notar a importância da junção, num único texto, das regras sobre formação do contrato e sobre a venda internacional de mercadorias.

Por fim, acautelou-se também que a Convenção da Viena só vigoraria se conseguisse granjear mais Estados Contratantes do que as Convenções da Haia de 1964. É esta a razão de se exigir no artigo 99.º, n.º 1, a vinculação internacional de 10 Estados para a entrada em vigor internacional da Convenção.

* 2. Características gerais

Relatado, em termos necessariamente breves, o percurso que levou a aprovação da Convenção sobre a Venda Internacional de Mercadorias, quero agora abordar aquilo que se pode designar por características gerais.

Como já referi, atualmente são 94 os Estados Contratantes da Convenção sobre a Venda Internacional de Mercadorias. É, no campo do comércio internacional, a segunda Convenção com maior número de Estados Contratantes (a primeira é a Convenção de Nova Iorque sobre Reconhecimento e Execução de Sentenças Arbitrais Estrangeiras). Quase todos os principais Estados na área do comércio internacional são Estados Contratantes da Convenção: as exceções são o Reino Unido e a Índia.

** A) Conciliação de diferentes sistemas jurídicos e económicos

A Convenção de Viena sobre a Venda Internacional de Mercadorias uniformiza o direito material privado em matéria de formação de contrato e venda internacional de mercadorias. Fê-lo, procurando conciliar os principais sistemas jurídicos e económicos existentes. Essa tarefa obrigou a formular /conceitos novos/ (v.g. o conceito de violação fundamental previsto no artigo 25.º da CVIM) e a utilizar outros próprios de determinada cultura jurídica que são estranhos a outras culturas jurídicas.

Em qualquer dos casos, a Convenção /obriga/ o intérprete e o aplicador do Direito a ter uma atitude de especial abertura. O intérprete e o aplicador do Direito devem ter especial cuidado e atenção para não cair na tentação de interpretar os conceitos da Convenção de acordo com a sua própria cultura jurídica e o seu próprio direito material.

A Convenção de Viena sobre Venda Internacional de Mercadorias preocupa-se, verdadeiramente, em garantir uma interpretação uniforme das suas disposições e evitar uma "renacionalização" das mesmas através de uma interpretação e aplicação sob o prisma da /lex fori/. É, por isso, particularmente importante o artigo 7.º, que estabelece regras de interpretação das disposições da Convenção e de integração de lacunas. Não é o meu objetivo analisar aqui este importante preceito, mas assinalo que este preceito /(i)/ expressamente refere o carácter internacional da Convenção, o que tem sido entendido como impondo uma interpretação autónoma das suas disposições; este preceito /(ii)/ assinala a necessidade de promover a uniformidade de aplicação, o que nos aponta para tomarmos em consideração a jurisprudência; e este preceito /(iii)/ exige também que se respeite a boa-fé no comércio internacional, o que tem sido visto como uma garantia de tomada em consideração dos usos do comércio internacional.

Interessa-me agora referir um pouco mais a necessidade de promover a uniformidade de aplicação. Como disse, esta diretriz tem sido entendida como dando relevo à jurisprudência. Saliento que o intérprete e o aplicador não devem apenas atender à jurisprudência do seu Estado. Tanto quanto possível - e como veremos, é bastante possível - o intérprete e o aplicador devem atender à jurisprudência dos vários Estados contratantes da CISG. Só assim se garante uma verdadeira uniformidade de aplicação. Aqui, quero destacar as bases de dados disponíveis na /Internet/ que permitem facilmente contactar com uma enorme fonte de decisões de litígios mediante a aplicação da Convenção. Destaco aqui a base de dados CLOUT (da CNUDCI), a base de dados PACE e também a Base de Dados brasileira disponível em www.cisg-brasil.net. Também é interessante verificar às opiniões do Conselho Consultivo da CVIM. Trata-se de uma entidade privada, que visa promover a interpretação uniforme da Convenção. Os seus membros são, geralmente, académicos e pessoas ligadas ao comércio internacional. Emitem opiniões sobre questões relevantes da Convenção, com vista a promover uma interpretação uniforme das suas disposições.

** B) Utilização de conceitos indeterminados

Outra característica é utilização muito frequente de conceitos indeterminados. Na definição de violação fundamental (art. 25.º), usa-se o conceito indeterminado de "pessoa razoável". No artigo 39.º, n.º 1, o comprador perde o direito de invocar a falta de conformidade se não o fizer num "prazo razoável".

O recurso a conceitos indeterminados permite uma margem de apreciação que permite uma modelação do resultado em face de todas as circunstâncias do caso concreto. O recurso também se justifica por a venda internacional de mercadorias poder assumir configurações muito variadas, não sendo fácil (eventualmente não sendo mesmo possível) encontrar uma solução /rígida e precisa/ que seja adequada a todas essas configurações.

Esta flexibilização também é compreensível se atendermos ao relevo da autonomia privada. No essencial, e por força do artigo 6.º da Convenção, todas as suas disposições são supletivas, isto é, podem ser afastadas mediante acordo das partes. A aplicação da própria Convenção pode ser afastada mediante acordo das partes.

Por vezes, o recurso a conceitos indeterminados foi a forma encontrada de ultrapassar dificuldades políticas (posições contraditórias) na elaboração dos artigos: é o caso do conceito de "motivo razoável", no artigo 44.º.

Por fim, o recurso a conceitos indeterminados é também o preço a pagar pela conciliação de diversos sistemas jurídicos.

** C) Relativo favorecimento do comprador

Alguns autores sustentam que as regras da Convenção favorecem o comprador. Outros referem que o Direito nacional dos países da família Romano-Germânica tende a favorecer o vendedor, com regras a impor o exame dos bens pelo comprador e o dever de notificar o devedor de quaisquer defeitos.

Não há dúvidas que alguns conceitos - como o de conformidade (art. 35.º) - são mais favoráveis para o comprador (pelo menos se comparados com o regime interno). Isto deve-se, no essencial, às posições manifestadas pelos países em vias de desenvolvimento. Um exemplo claro desta dicotomia pode ser visto nas regras de exame dos bens e notificação do vendedor de falta de conformidade (arts. 38.º, 39.º e 44.º). A Convenção manteve obrigações de exame dos bens e de notificação do vendedor, que beneficiam este último, apesar de os Estados em vias de desenvolvimento terem pressionado em favor da eliminação do dever de notificação. Ainda assim, a verdade é que os prazos de exame e notificação são fixados com recurso a conceitos indeterminados: o exame tem de ser efetuado "no mais curto prazo possível, tendo em conta as circunstâncias"; a notificação "num prazo razoável". Estes conceitos indeterminados permitem modelar a solução atendendo às circunstâncias do caso concreto, o que muitas vezes permite acautelar a preocupação dos países em vias de desenvolvimento: apesar de os compradores sediados nesses países não estarem habituados a estas obrigações, a não fixação de regras rígidas e precisas permite acautelar os interesses destes, mesmo em casos em que o exame ou notificação não foi efetuada do modo mais célere possível.

No que se refere à notificação, a Convenção consagrou uma solução peculiar. A falta de notificação não impede que o comprador consiga uma redução do preço ou uma indemnização por perdas e danos, salvo quanto ao lucro cessantes, desde que ele tenha um "motivo razoável" para não ter feito a notificação (art. 44.º).

De qualquer modo, seja qual for a vossa opinião sobre o equilíbrio das partes na Convenção, não é possível esquecer que as partes podem recompor esse equilíbrio. Como já disse, no essencial a Convenção tem regras supletivas. As partes podem afastar as soluções da Convenção e gizar o seu próprio equilíbrio.

** D) Uniformização limitada do Direito material

A Convenção de Viena sobre a Venda Internacional de Mercadorias é um instrumento muito importante e muito bem sucedido na área do comércio internacional.

Ainda assim, é importante ter presente que ela só uniformiza o Direito material da formação do contrato de venda e dos direitos e obrigações por ele gerados.

A Convenção não regula, por exemplo, a validade do contrato nem os efeitos reais deste. Isto significa que a uniformização do contrato de venda internacional de mercadoria /não/ é exaustiva. E, nas matérias não reguladas pela Convenção, temos ainda de recorrer ao Direito de Conflitos do foro para determinar qual o Direito material aplicável.

Acresce que os Estados podem efetuar uma reserva, nos termos do artigo 92.º da Convenção, no sentido de que só se vinculam ou à Parte II (formação do contrato) ou à Parte III (direitos e obrigações das partes). Nos Estados que façam estas reservas, o âmbito da uniformização é ainda menor. China, Brasil e Portugal não fizeram esta reserva.

** E) Atribuição de carácter vinculativo aos usos do comércio

A solução que consta do artigo 9.º, n.º 2, da Convenção é extremamente interessante:

#+begin_quote
 2 - Salvo acordo em contrário, considera-se que as partes aplicaram tacitamente ao contrato ou à sua formação um uso que conhecessem ou devessem ter conhecimento e que, no comércio internacional, é amplamente conhecido e regularmente observado pelas partes em contratos do mesmo tipo, no ramo comercial considerado.
#+end_quote

Em primeiro lugar, porque a Convenção não define o conceito de uso ou uso do comércio internacional. Sustenta-se, ao abrigo do artigo 7.º, que o conceito de uso deve ser interpretado autonomamente, isto é, de forma independente dos Direitos nacionais dos Estados Contratantes. Uma definição possível é a seguinte:

#+begin_quote
Uso inclui todos os modos de atuação (incluindo omissões) que são geral e regularmente observados no âmbito de transações do comércio, mesmo que apenas numa área específica do comércio ou num determinado centro comercial.
#+end_quote

Os usos do artigo 9.º, n.º 2, têm de ser usos internacionais, ou seja, usos do comércio internacional.

O que de mais relevante parece ter o artigo 9.º, n.º 2, é que as partes não parecem ter de acordar na aplicação do uso internacional para este se aplicar e regular o contrato entre elas. Muitos autores referem que este artigo cria uma "ficção jurídica": a de que as partes quiseram que os usos do comércio internacional (amplamente conhecidos e de que as partes devessem ter conhecimento) se aplicassem à regulação da relação contratual mesmo que nada nessa relação permita inferir que as partes ponderaram e quiseram a aplicação desses usos.

Estes usos prevalecem sobre as regras da Convenção, em caso de conflito. Já não me parece que prevaleçam sobre os usos e práticas acordadas pelas partes (art. 9.º, n.º 1), uma vez que, nesse caso, há um acordo em contrário das partes (parte inicial do artigo 9.º, n.º 2). Em caso de conflito entre dois usos do comércio internacional (do art. 9.º, n.º 2) duas soluções foram avançadas pela doutrina: ou prevalece o uso que tem uma ligação mais estreita com a relação contratual ou nenhum dos usos é aplicável (eles anulam-se).

Amplamente conhecido e regularmente observado /não/ significa conhecido de e observado por todos. Significa que a maioria das pessoas envolvidas numa dada prática comercial (a que corresponde à relação contratual em análise) devem conhecer e observar o uso.

O uso tem de ser do comércio internacional, isto é, tem de se aplicar a relações contratuais internacionais. Pode ser um uso que existe apenas num determinado local (um determinado centro de comércio), desde que nesse centro se celebrem relações contratuais internacionais e que o uso seja amplamente conhecido e observado pela maioria das pessoas que celebram essas relações comerciais.

Exige-se ainda que as partes conheçam ou devessem conhecer: em regra o requisito de que o uso seja amplamente conhecido limita o funcionamento deste requisito subjetivo, isto é, se o uso é amplamente conhecido, em regras as partes que exercem a sua atividade comercial no local onde esse uso é amplamente conhecido terão o dever de o conhecer. Ainda assim, o requisito não é redundante, porque podem verificar-se situações em que a pessoa não conhece o uso amplamente conhecido em função de motivos justificativos.

As questões de saber se um determinado uso existe, se é um uso do comércio internacional e se é amplamente conhecido e observado parecem ser questões de facto. Como tal, parece que cabe à parte que se pretende valer do uso, alegar e provar estes elementos.

Deixo-vos com uma última interrogação: poderão os INCOTERMS e os Princípios UNIDROIT dos Contratos Comerciais Internacionais ser considerados usos internacionais para efeitos do artigo 9.º, n.º 2, da Convenção? A questão tem sido muito discutida na doutrina, mas eu deixaria a análise da mesma para a minha segunda preleção, em que abordarei estes dois instrumentos.

* Abreviaturas

CNUDCI - Comissão das Nações Unidas para o Direito Comercial Internacional

CVIM - Convenção de Viena sobre Venda Internacional de Mercadorias

UNIDROIT - /Institut international pour l’unification du droit privé/

* Footnotes
[fn:2] ‘Rapport sur le droit comparé de vente par le “Institut für ausländisches und internationales Privatrecht” de Berlin’ (Rome: Pallotta (1929)), reproduced inter alia in Rabel, Ges Aufs, vol III, p 381 et seq.

[fn:1] Report A of the Institute, RabelsZ 3 (1929).
