#+TITLE: Introdução à Convenção de Viena sobre Venda Internacional de Mercadorias
#+AUTHOR: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: date:nil toc:nil num:nil
#+LATEX_COMPILER: xelatex


* 1. Contexto histórico
** A) Primeiros passos

Os primeiros esforços de unificação legislativa do Direito da venda internacional começaram nos anos 20 do século passado. Normalmente atribui-se a primeira sugestão de unificação da lei do contrato de venda internacional de mercadorias a Ernst Rabel.

Ernst Rabel foi diretor do Instituto, à data, Kaiser Wilhelm - hoje Max Planck -, para o Direito estrangeiro e Direito Internacional Privado, criado em 1926. Um dos estudos efetuados pelo Instituto foi um estudo comparativo sobre o Direito da venda internacional de mercadorias.

Também em 1926 a Liga das Nações fundou, em Roma, o /Institut international pour l’unification du droit privé/ (UNIDROIT). O UNIDROIT foi um passo importante para a unificação do Direito da venda internacional de mercadorias. O seu [[https://www.unidroit.org/english/presentation/statute.pdf][Estatuto]] estabelece, no artigo 1.º a missão de:

#+begin_quote
(...) examine  ways  of  harmonising  and  coordinating  the private law of States and of groups of States, and to prepare gradually for the adoption by the various States of uniform rules of private law.
#+end_quote

Em 1928, Ernst Rabel, membro da direção do UNIDROIT, sugeriu que o primeiro projeto de unificação fosse sobre o Direito material da venda internacional de mercadorias. Rabel apresentou, em 1929, dois relatórios: /(i)/ um relatório provisório relativo às possibilidades de unificação do Direito da venda de mercadorias[fn:1]; e /(ii)/ um relatório sobre o Direito comparado da venda internacional de mercadorias, que viria a ser conhecido por "Relatório Azul"[fn:2].

Em 1930, o UNIDROIT estabeleceu uma comissão com vista a trabalhar no projeto de lei uniforme de venda. A Comissão contava entre os seus membros, para além de Rabel, com representantes dos sistemas jurídicos do /Common Law/, do sistema francês, alemão e dos países Escandinavos.

O primeiro /draft/ foi apresentado em 1935. Este /draft/ era fortemente influenciado pelo estudo de Direito comparado da venda internacional de Rabel.

Quatro anos mais tarde, em 1939, foi apresentado um segundo /draft/. A Segunda Guerra Mundial suspendeu as negociações que só retomaram em 1950.

** B) As Convenções UNIDROIT de 1964
:PROPERTIES:
:ID:       bcab76a9-f161-4285-b7a5-3e8ca6f36a56
:END:

Em 1951, o UNIDROIT realizou uma conferência de 21 Estados na Haia. Foram enviados novos /drafts/ do projeto de lei uniforme da venda internacional de mercadorias em 1956 e 1963 e iniciaram-se trabalhos no projeto de lei uniforme sobre a formação de contratos de venda internacional de mercadorias.

Em 1964, realizou-se nova conferência diplomática na Haia, desta feita com a participação de 28 Estados, que culminou com a aprovação das duas convenções UNIDROIT de 1964:  uma contendo a [[https://www.unidroit.org/instruments/international-sales/ulis-1964/][Lei uniforme sobre venda internacional de mercadorias]] e outra a [[https://www.unidroit.org/instruments/international-sales/ulfc-1964/][Lei uniforme sobre a formação dos contratos de venda internacional de mercadorias]].

O objetivo destas Convenções era a unificação mundial do Direita da venda internacional de mercadorias. Apesar de terem entrado internacionalmente em vigor, estas Convenções não podem considerar um sucesso quando analisadas em função daquele objetivo: apenas nove Estados se vincularam a estas Convenções.

As razões avançadas para este reduzido número de Estados contratantes são variadas. As que me parecem mais relevantes são o elevado grau de abstração de vários conceitos fulcrais das leis uniformes e, sobretudo, a ideia de que as leis uniformes não tomaram em consideração os interesses dos Estados em vias de desenvolvimentos ou dos Estados de leste, que não particparam na elaboração e aprovação destas leis uniformes. Outra razão avançada é a não vinculação de alguns dos Estados mais importantes no comércio internacional, como os Estados Unidos da América e a França.

Ainda assim, estas duas leis uniformes foram relevantes. Elas tiveram uma relevante importância na prática jurisprudencial alemã, italiana, belga, luxemburguesa e holandesa. E marcaram também a elaboração da Convenção de Viena sobre Internacional de Mercadorias.

** C) A CNUDCI e a génese da CVIM

Em 1966 a Assembleia Geral das Nações Unidas estabeleceu a Comissão das Nacções Unidas para o Direito Comercial Internacional (CNUDCI) como comissão permanente, com o mandato de promover a progressiva harmonização e unificação do Direito do comércio internacional.

A primeira questão com que se deparou, no que se referia à promoção da unificação do direito da venda internacional de mercadorias, era a de tentar promover uma adoção mais ampla das Convenções de 1964, como fez com a Convenção de Nova Iorque de 1958 sobre o Reconhecimento e Execução de Sentenças Arbitrais Estrangeiras /ou/ preparar uma nova Convenção.

Para responder a esta questão enviou o texto das Convenções de 1964, juntamente com o Relatório Explicativo elaborado pelo Professor André Tunc, a vários Governos, pedindo comentários e a posição sobre uma eventual vinculação às Convenções. A CNUDCI chegou à conclusão de que as Convenções não seriam um sucesso: muitos Estados estavam preocupados que as Convenções refletiam as tradições e realidades económicas dos países  europeus.

A CNUDCI decidiu assim avançar para a elaboração de uma nova Convenção, que viria a ser a Convenção de Viena sobre Venda Internacional de Mercadorias.

O processo de elaboração da Convenção pode dividir-se em três fases.

A primeira fase decorreu entre 1970 e 1977. Foi constituído um Grupo de Trabalho que preparou projetos para as reuniões plenárias da CNUDCI. Estes projetos partiram da análise, pelo Grupo de Trabalho, das duas leis uniformes. Em 1976, o Grupo de Trabalho concluiu e aprovou, por unanimidade, o projeto de Convenção sobre a Venda Internacional de Mercadorias, que estabelecia os direitos e obrigações de vendedores e compradores na venda internacional. Em 1977, o Grupo de Trabalho concluiu o projeto de Convenção sobre a Formação do Contrato de Venda Internacional de Mercadorias.

O início da segunda fase dá-se com a reunião da CNUDCI em Viena, de maio a junho de 1977. Nesta reunião a CNUDCI reviu, concluiu e aprovou o projeto de Convenção sobre a Venda Internacional. Um ano mais tarde, em maio e junho de 1978, o projeto de Convenção sobre a formação do contrato foi analisado e foi decidido juntar os dois projetos. O projeto de Convenção sobre Contratos de Venda Internacional de Mercadorias foi concluído em junho de 1978 e ficou conhecido como o /New York Draft/.

O /New York Draft/ foi enviado para os governos dos Membros das Nações Unidas. Ele e os comentários recebidos foram a base da Convenção de Viena sobre a Venda Internacional de Mercadorias.

A terceira e última fase inicia-se com a Conferência das Nações Unidas que teve lugar em Viena, de 10 de março a 11 de abril de 1980. Participaram nesta conferência 62 Estados e 8 organizações internacionais. Foram formados dois comitês: o primeiro trabalhou as normas substantivas (arts. 1 a 88 da CVIM); o segundo as disposições finais (arts. 89 a 101) e preparou um protocolo para a Convenção sobre prescição em matéria de venda internacional de mercadorias, de modo a adaptar esta convenção à futura Convenção sobre a Venda Internacional de Mercadorias. A Convenção foi aprovada em 11 de março de 1980 e entrou internacionalmente em vigor em 1 de janeiro de 1988, doze meses passados da data da 10.ª adesão. Hoje são 94 os Estados contratantes.


** D) Razões do sucesso da CVIM

Pode perguntar-se porque teve a Convenção sobre a Venda Internacional de Mercadorias sucesso e as Convenções da Haia de 1964 não.

A verdade é que a Convenção corrigiu aquele que parece ter sido o maior "pecado" das Convenções. Participaram na elaboração das Convenções da Haia 28 Estados, dos quais 19 eram da Europa Ocidental, 3 da Europa de Leste (mas a ex-URSS não participou) e apenas 5 eram da África, Ásia e América do Sul. Este desiquilíbrio fomentou a perceção - certa ou errada, isso é irrelevante - de que as Convenções da Haia não tomavam em consideração os interesses de Estados que não os da Europa Ocidental.

A CNUDCI estabeleceu uma distribuição regional específica para os seus membros, de modo a garantir a representação das várias regiões geográficas e dos princípais sistemas jurídicos e económicos mundiais. Assim, 9 membros eram da África, 7 membros da Ásia, 5 da Europa de leste, 6 da América do Sul e 9 dos Estados ocidentais.

Consequentemente, e em contraste com as Convenções da Haia de 1964, a Convenção sobre a Venda Internacional de Mercadorias procura conciliar diferentes tradições jurídicas e utiliza mais conceitos indeterminados de modo a facilitar a vinculação internacional de mais Estados. Nesse mesmo sentido, também parece ser de notar a importância da junção, num único texto, das regras sobre formação do contrato e sobre a venda internacional de mercadorias.

Por fim, acautelou-se também que a Convenção da Viena só vigoraria se conseguisse granjear mais Estados Contratantes do que as Convenções da Haia de 1964. É esta a razão de se exigir no artigo 99.º, n.º 1, a vinculação internacional de 10 Estados para a entrada em vigor internacional da Convenção.

* 2. Características gerais

Relatado, em termos necessariamente breves, o percurso que levou a aprovação da Convenção sobre a Venda Internacional de Mercadorias, quero agora abordar aquilo que se pode designar por características gerais.

Como já referi, atualmente são 94 os Estados Contratantes da Convenção sobre a Venda Internacional de Mercadorias. É, no campo do comércio internacional, a segunda Convenção com maior número de Estados Contratantes (a primeira é a Convenção de Nova Iorque sobre Reconhecimento e Execução de Sentenças Arbitrais Estrangeiras). Quase todos os principais Estados na área do comércio internacional são Estados Contratantes da Convenção: as exceções são o Reino Unido e a Índia.

** A) Conciliação de diferentes sistemas jurídicos e económicos

A Convenção de Viena sobre a Venda Internacional de Mercadorias uniformiza o direito material privado em matéria de formação de contrato e venda internacional de mercadorias. Fê-lo, procurando conciliar os principais sistemas jurídicos e económicos existentes. Essa tarefa obrigou a formular /conceitos novos/ (v.g. o conceito de violação fundamental previsto no artigo 25.º da CVIM) e a utilizar outros próprios de determinada cultura jurídica que são estranhos a outras culturas jurídicas.

Em qualquer dos casos, a Convenção /obriga/ o intérprete e o aplicador do Direito a ter uma atitude de especial abertura. O intérprete e o aplicador do Direito devem ter especial cuidado e atenção para não cair na tentação de interpretar os conceitos da Convenção de acordo com a sua própria cultura jurídica e o seu próprio direito material.

A Convenção de Viena sobre Venda Internacional de Mercadorias preocupa-se, verdadeiramente, em garantir uma interpretação uniforme das suas disposições e evitar uma "re-nacionalização" das mesmas através de uma interpretação e aplicação sob o prisma da /lex fori/. É, por isso, particularmente importante o artigo 7.º, que estabelece regras de interpretação das disposições da Convenção e de integração de lacunas. Não é o meu objetivo analisar aqui este importante preceito, mas assinalo que este preceito /(i)/ expressamente refere o carácter internacional da Convenção, o que tem sido entendido como impondo uma interpretação autónoma das suas disposições; este preceito /(ii)/ assinala a necessidade de promover a uniformidade de aplicação, o que nos aponta para tomarmos em consideração a jurisprudência; e este preceito /(iii)/ exige também que se respeite a boa-fé no comércio internacional, o que tem sido visto como uma garantia de tomada em consideração dos usos do comércio internacional.

Interessa-me agora referir um pouco mais a necessidade de promover a uniformidade de aplicação. Como disse, esta diretriz tem sido entendida como dando relevo à jurisprudência. Saliento que o intérprete e o aplicador não devem apenas atender à jurisprudência do seu Estado. Tanto quanto possível - e como veremos, é bastante possível - o intérprete e o aplicador devem atender à jurisprudência dos vários Estados contratantes da CISG. Só assim se garante uma verdadeira uniformidade de aplicação.

** B) Utilização de conceitos indeterminados
** C) Relativo favorecimento do comprador
** D) Uniformização limitada do Direito material
** E) Atribuição de carácter vinculativo aos usos do comércio

* Abreviaturas

CNUDCI - Comissão das Nações Unidas para o Direito Comercial Internacional

CVIM - Convenção de Viena sobre Venda Internacional de Mercadorias

UNIDROIT - /Institut international pour l’unification du droit privé/

* Footnotes
[fn:2] ‘Rapport sur le droit comparé de vente par le “Institut für ausländisches und internationales Privatrecht” de Berlin’ (Rome: Pallotta (1929)), reproduced inter alia in Rabel, Ges Aufs, vol III, p 381 et seq.

[fn:1] Report A of the Institute, RabelsZ 3 (1929).
